const mongoose = require('mongoose');

const sinavSchema = new mongoose.Schema({
   sinav:{type:String},
   aciklama:{type:String},
   durum:Boolean,
   sinavtarih:Date,
   sinavlar: [{
    sinavadi:String,
    ogrencino:Number,
      tc:Number,
      adiSoyadi:String,
      sinifSube:String,
      turkce:Number,
      turkceD:Number,
      turkceY:Number,
      matematik:Number,
      matematikD:Number,
      matematikY:Number,
      tarih:Number,
      tarihD:Number,
      tarihY:Number,
      din:Number,
      dinD:Number,
      dinY:Number,
      ingilizce:Number,
      ingilizceD:Number,
      ingilizceY:Number,
      fen:Number,
      fenD:Number,
      fenY:Number,

      sozelturkce:Number,
      sozelturkceD:Number,
      sozelturkceY:Number,
      sozelmatematik:Number,
      sozelmatematikD:Number,
      sozelmatematikY:Number,
      sozeltarih:Number,
      sozeltarihD:Number,
      sozeltarihY:Number,
      sozeldin:Number,
      sozeldinD:Number,
      sozeldinY:Number,
      sozelingilizce:Number,
      sozelingilizceD:Number,
      sozelingilizceY:Number,
      sozelfen:Number,
      sozelfenD:Number,
      sozelfenY:Number,

      sayisalturkce:Number,
      sayisalturkceD:Number,
      sayisalturkceY:Number,
      sayisalmatematik:Number,
      sayisalmatematikD:Number,
      sayisalmatematikY:Number,
      sayisaltarih:Number,
      sayisaltarihD:Number,
      sayisaltarihY:Number,
      sayisaldin:Number,
      sayisaldinD:Number,
      sayisaldinY:Number,
      sayisalingilizce:Number,
      sayisalingilizceD:Number,
      sayisalingilizceY:Number,
      sayisalfen:Number,
      sayisalfenD:Number,
      sayisalfenY:Number,

      toplamD:Number,
      toplamY:Number,
      toplam:Number,
      lgspuan:Number,
      lgssinif:Number,
      lgskurum:Number,
      lgsilce:Number,
      lgsil:Number,
      lgsgenel:Number,

  
  }],
   
 })

module.exports = mongoose.model('Sinavlar', sinavSchema);