const mongoose = require('mongoose');

        const userSchema = new mongoose.Schema({
            name: { type: String, required:true},
            surname: { type: String, required:true},
            email: String ,
            ogrencino: { type: String, required:true, unique:true } ,
            tc: { type: String, required:true, unique:true } ,
            password: { type: String, required:true},
            telefon:{ type: String, required:true},
            veli: { type: String, required:true},
            role: String,
            taksit: Number,
            ilktaksit: Date,
            ucret: Number,
            sinif: { type: String, required:true},
            token: String,
            ekleyen: String,
            password_link: String,
            durum: Boolean,
           date: {
             type: Date,
             default: Date.now
            },
          odemeler: [{
             odeme:Number,
            odemetarihi:Date}],
          yapilanodemeler: [{
              odeme:Number,
             odemetarihi:Date,
              durum:Boolean}],
              /*
         sinavlar: [{
                sinavadi:String,
                ogrencino:Number,
                  tc:Number,
                  adiSoyadi:String,
                  sinifSube:String,
                  turkce:Number,
                  turkceD:Number,
                  turkceY:Number,
                  matematik:Number,
                  matematikD:Number,
                  matematikY:Number,
                  tarih:Number,
                  tarihD:Number,
                  tarihY:Number,
                  din:Number,
                  dinD:Number,
                  dinY:Number,
                  ingilizce:Number,
                  ingilizceD:Number,
                  ingilizceY:Number,
                  fen:Number,
                  fenD:Number,
                  fenY:Number,
            
                  sozelturkce:Number,
                  sozelturkceD:Number,
                  sozelturkceY:Number,
                  sozelmatematik:Number,
                  sozelmatematikD:Number,
                  sozelmatematikY:Number,
                  sozeltarih:Number,
                  sozeltarihD:Number,
                  sozeltarihY:Number,
                  sozeldin:Number,
                  sozeldinD:Number,
                  sozeldinY:Number,
                  sozelingilizce:Number,
                  sozelingilizceD:Number,
                  sozelingilizceY:Number,
                  sozelfen:Number,
                  sozelfenD:Number,
                  sozelfenY:Number,
            
                  sayisalturkce:Number,
                  sayisalturkceD:Number,
                  sayisalturkceY:Number,
                  sayisalmatematik:Number,
                  sayisalmatematikD:Number,
                  sayisalmatematikY:Number,
                  sayisaltarih:Number,
                  sayisaltarihD:Number,
                  sayisaltarihY:Number,
                  sayisaldin:Number,
                  sayisaldinD:Number,
                  sayisaldinY:Number,
                  sayisalingilizce:Number,
                  sayisalingilizceD:Number,
                  sayisalingilizceY:Number,
                  sayisalfen:Number,
                  sayisalfenD:Number,
                  sayisalfenY:Number,
            
                  toplamD:Number,
                  toplamY:Number,
                  toplam:Number,
                  lgspuan:Number,
                  lgssinif:Number,
                  lgskurum:Number,
                  lgsilce:Number,
                  lgsil:Number,
                  lgsgenel:Number,
                  
               
              
              }],
              */

           }) 
        
         module.exports = mongoose.model('Users', userSchema);
 